not parallel processing gyp file
I'm working on a old platforms,when I run ```node-gyp configure```,node-gyp report one error of python 
> ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

check this : http://bugs.python.org/issue3770

I suggest not parallel processing because usually we don't have so manay files to parse.

github.com/joyent/node had closed the issue of the same problem,see :

https://github.com/joyent/node/issues/6640